# Site settings
name: Shivaanee
title: Shivaanee | Personal Website
url: https://shivaanee.github.io/
baseurl: ''
email: eshiva200@gmail.com
cover: https://shivaanee.github.io/img/og.png
logo: https://shivaanee.github.io/img/emojis/technologist.png
resume: https://shivaanee.github.io/Resume.pdf
social:
  - title: email
    url: mailto:eshiva200@gmail.com
  - title: github
    url: https://github.com/shivaanee
  - title: linkedin
    url: https://linkedin.com/in/shivaanee

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
